title: Toastify
repository: aleab/toastify

encoding: utf-8
markdown: kramdown
theme: jekyll-theme-slate

google_analytics: UA-105184643-4
show_downloads: true

github:
  owner_url: https://github.com/aleab
  repository_url: https://github.com/aleab/toastify
  forked_repo_url: https://github.com/nachmore/toastify

plugins:
  - jekyll-mentions
  - jemoji
